config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { registrations: "users/registrations", sessions: "users/sessions" }
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'home#home'

  mount ActionCable.server, at: '/cable'

  # ~ ~ ~   ~ ~ ~   ~ ~ ~   ~ ~ ~   ~ ~ ~
  #            home controller
  # ~ ~ ~   ~ ~ ~   ~ ~ ~   ~ ~ ~   ~ ~ ~
  get 'dashboard', to: 'home#dashboard'

  # ~ ~ ~   ~ ~ ~   ~ ~ ~   ~ ~ ~   ~ ~ ~
  #          projects controller
  # ~ ~ ~   ~ ~ ~   ~ ~ ~   ~ ~ ~   ~ ~ ~
  resources :projects, only: [:new, :create, :show]
  get 'project/invite/:id', to: 'projects#invite_users', as: 'invite_users'
  post 'projects/invite', to: 'projects#invite_users_create', as: 'invite_users_create'
  get 'project/invite/accept/:proj_id', to: 'projects#accept_project_invitation', as: 'accept_project_invitation'

  # ~ ~ ~   ~ ~ ~   ~ ~ ~   ~ ~ ~   ~ ~ ~
  #          features controller
  # ~ ~ ~   ~ ~ ~   ~ ~ ~   ~ ~ ~   ~ ~ ~
  get 'features/new/:proj_id', to: 'features#new', as: 'new_feature'
  post 'features', to: 'features#create', as: 'features'
  post 'features/:proj_id/completed/:feat_id', to: 'features#feature_completed', as: 'feature_completed'

  # ~ ~ ~   ~ ~ ~   ~ ~ ~   ~ ~ ~   ~ ~ ~
  #          messages controller
  # ~ ~ ~   ~ ~ ~   ~ ~ ~   ~ ~ ~   ~ ~ ~
  resources :messages, only: [:create]
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  before_action :home_to_dashboard, only: [:home]
  before_action :unauthorised_access, only: [:dashboard]

  def home
  end

  def dashboard
    @projects = current_user.projects.includes(:project_users)
    @accepted_projects = @projects.where('project_users.status = 1')
    @pending_projects = @projects.where('project_users.status = 0')
  end

  private
  # if current user, redirect home to dashboard
  def home_to_dashboard
    redirect_to dashboard_path if current_user
  end

end

app/views/home/callback.html.erb
<div class="container">
  <h2 class="text-center">Authorised!</h2>
</div>

app/views/home/dashboard.html.erb
<button id="push-notification">Push</button>

<div id="dashboard-header">
  <p id="dashboard-header-title">
    Manage Your Projects
  </p>
</div>

<div class="container">

  <%= link_to 'New Project', new_project_path, id: 'dashboard-new-project' %>

  <br />

  <div class="row">
    <div class="col-md-6 ml-auto mr-auto">

      <div class="row">
        <div class="col-8 ml-auto mr-auto">

          <h4 class="text-center">Your Projects</h4>

          <ul class="list-group">
            <% @accepted_projects.each do |proj| %>
              <%= link_to proj.title, project_path(proj), class: "list-group-item list-group-item-action" %>
            <% end %>
          </ul>

        </div>
      </div>

    </div>

    <div class="col-md-6 ml-auto mr-auto">

      <div class="row">
        <div class="col-8 ml-auto mr-auto">

          <h4 class="text-center">Pending Invitations</h4>

          <ul class="list-group">
            <% @pending_projects.each do |proj| %>
              <li class="list-group-item">
                <%= proj.title %>
                <%= link_to 'Accept Invitation', accept_project_invitation_path(proj_id: proj.id), class: 'btn btn-xs btn-success' %>
              </li>
            <% end %>
          </ul>

        </div>
      </div>

    </div>
  </div>
</div>


<script type="text/javascript">
  $(document).ready( () => {
    if ('serviceWorker' in navigator) {
      window.addEventListener('load', function() {
        navigator.serviceWorker.register('/serviceworker.js', { scope: './' }).then(function(registration) {
          // Registration was successful
          console.log('ServiceWorker registration successful with scope: ', registration.scope);

          registration.pushManager.getSubscription().then( function(subscription) {
              isSubscribed = !(subscription === null);

              if (isSubscribed) {
                console.log('User IS subscribed.');
              } else {
                console.log('User is NOT subscribed.');
                subscribeUser(registration, <%= current_user.id %>);
              }
          });

        }, function(err) {
          // registration failed :(
          console.log('ServiceWorker registration failed: ', err);
        });
      });
    }

    $('#push-notification').click( () => {
      const url = 'workers/push/<%= current_user.id %>'
      fetch(url);
    })
  })
</script>

app/views/home/github_auth.html.erb
<div class="container">
  <h2 class="text-center">Authorise this Application to use Your Github Account!</h2>

  <br />

  <div align="center">
    <a href="https://github.com/login/oauth/authorize?client_id=893624586408ad9146c0&state=<%= @state %>" class="btn btn-success">Authorise</a>
  </div>
</div>

app/views/home/home.html.erb
<div id="jumbotron">
  <div id="jumbotron-overlay">
    <p id="jumbo-title">
      ManaGit
      <small id="jumbo-title-small">(Manage - It)</small>
    </p>

    <p id="jumbo-subtitle">
      Your Solution to Managing Development Workflows
    </p>

    <%= link_to 'Get Started', new_user_session_path, id: 'jumbo-login-button' %>
  </div>
</div>