config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { registrations: "users/registrations", sessions: "users/sessions" }
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'home#home'

  mount ActionCable.server, at: '/cable'

  # ~ ~ ~   ~ ~ ~   ~ ~ ~   ~ ~ ~   ~ ~ ~
  #            home controller
  # ~ ~ ~   ~ ~ ~   ~ ~ ~   ~ ~ ~   ~ ~ ~
  get 'dashboard', to: 'home#dashboard'

  # ~ ~ ~   ~ ~ ~   ~ ~ ~   ~ ~ ~   ~ ~ ~
  #          projects controller
  # ~ ~ ~   ~ ~ ~   ~ ~ ~   ~ ~ ~   ~ ~ ~
  resources :projects, only: [:new, :create, :show]
  get 'project/invite/:id', to: 'projects#invite_users', as: 'invite_users'
  post 'projects/invite', to: 'projects#invite_users_create', as: 'invite_users_create'
  get 'project/invite/accept/:proj_id', to: 'projects#accept_project_invitation', as: 'accept_project_invitation'

  # ~ ~ ~   ~ ~ ~   ~ ~ ~   ~ ~ ~   ~ ~ ~
  #          features controller
  # ~ ~ ~   ~ ~ ~   ~ ~ ~   ~ ~ ~   ~ ~ ~
  get 'features/new/:proj_id', to: 'features#new', as: 'new_feature'
  post 'features', to: 'features#create', as: 'features'
  post 'features/:proj_id/completed/:feat_id', to: 'features#feature_completed', as: 'feature_completed'

  # ~ ~ ~   ~ ~ ~   ~ ~ ~   ~ ~ ~   ~ ~ ~
  #          messages controller
  # ~ ~ ~   ~ ~ ~   ~ ~ ~   ~ ~ ~   ~ ~ ~
  resources :messages, only: [:create]
end

app/models/project.rb
class Project < ApplicationRecord
  has_many :project_users
  has_many :users, through: :project_users

  has_many :features
  has_many :messages

  validates_presence_of :title, :owner

  def add_to_users(user)
    self.users << user
  end

  def is_owner_or_not(user)
    self.owner == user.id
  end

  def get_confirmed_users
    self.users.select { |u| ProjectUser.find_by(user_id: u.id, project_id: self.id).status == "accepted" }
  end

  def get_unconfirmed_users
    self.users.select { |u| ProjectUser.find_by(user_id: u.id, project_id: self.id).status == "pending" }
  end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_action :unauthorised_access
  before_action :owner_only, only: [:invite_users]
  before_action :accepted_users_only, only: [:show]

  def new
    @project = Project.new
  end

  def create
    @project = Project.new(project_params)

    if @project.save
      @project.add_to_users(current_user)

      flash[:success] = "Created New Project"
      redirect_to dashboard_path
    else
      flash[:danger] = @project.errors.full_messages
      render :new
    end
  end

  def show
    @project = Project.includes(:features, :messages).find(params[:id])

    # owner will be boolean
    @owner = @project.is_owner_or_not(current_user)

    @pending_features = @project.features.where(status: 'pending')
    @bug_features = @project.features.where(status: 'bugs')
    @completed_features = @project.features.where(status: 'completed')

    @confirmed_users = @project.get_confirmed_users
    @unconfirmed_users = @project.get_unconfirmed_users

    @new_message = Message.new
    @messages = @project.messages.order('created_at DESC').last(5)
  end

  # form for inviting other users to join project
  def invite_users
    @project = Project.find(params[:id])
  end

  # action for inserting other users into project
  def invite_users_create
    @user = User.find_by_email_or_username(params[:username_or_email])

    if @user
      @project = Project.find(params[:project_id])
      @project.users << @user

      flash[:success] = "Successfully Invited User: #{@user.username}"
      redirect_to invite_users_path(params[:project_id])
    else
      flash[:danger] = "User Could Not Be Found"
      redirect_to invite_users_path(params[:project_id])
    end
  end

  # action for accepting project invitation
  def accept_project_invitation
    @project_user = ProjectUser.find_by(user_id: current_user.id, project_id: params[:proj_id])

    if @project_user.status == 'pending'
      @project_user.update_columns(status: 1)

      flash[:success] = 'Accepted Project Invitation'
      redirect_to dashboard_path
    else
      flash[:danger] = 'Invalid Action'
      redirect_to dashboard_path
    end
  end

  private
  def project_params
    params.require(:project).permit(:title, :owner)
  end

  def owner_only
    @project = Project.find(params[:id])

    if @project.owner != current_user.id
      flash[:danger] = "Unauthorised Access"
      redirect_to root_path
    end
  end

  def accepted_users_only
    @project = Project.find(params[:id])
    @project_user = ProjectUser.find_by(project_id: @project.id, user_id: current_user.id)

    if @project_user.status == "pending"
      flash[:danger] = "Unauthorised Access"
      redirect_to dashboard_path
    end
  end
end

app/views/projects/_close_feature.html.erb
<%= form_tag feature_completed_path(proj_id: p.id, feat_id: f.id), remote: true do %>

  <%= submit_tag 'Complete', class: 'close-feature-button', id: "com-feat-#{f.id}" %>

<% end %>

app/views/projects/_completed_feature.html.erb
<li class="lg-item" id="completed-#{feat.id}">
  <%= feat.name %>

  <br /><br />

  <div class="features-username">
    <p><%= feat.owner_name %></p>
    <p><%= feat.updated_at.strftime("%-d/%-m/%Y") %></p>
  </div>
</li>

app/views/projects/_uncompleted_feature.html.erb
<li class="lg-item" id="uncompleted-feat-<%= feat.id %>">
  <%= feat.name %>

  <br /><br />

  <div class="features-username">
    <p><%= feat.owner_name %></p>
    <p><%= feat.created_at.strftime("%-d/%-m/%Y") %></p>
  </div>

  <% if feat.is_owner_or_not(user) %>
    <div class="close-feature-form-div" id="close-feature-form-<%= feat.id %>">
      <%= render 'projects/close_feature', p: proj, f: feat %>
    </div>
  <% end %>
</li>

app/views/projects/invite_users.html.erb
<div class="container">
  <h2 class="text-center">Invite other Users to join <%= @project.title %></h2>

  <br />

  <%= form_tag invite_users_create_path do %>

    <div class="row">
      <div class="col-md-6 ml-auto mr-auto">
        <label for="invite_users">Enter a Username or Email (case sensitive)</label> <br />
        <%= text_field_tag :username_or_email, nil, class: 'form-control', autofocus: true %>
      </div>
    </div>

    <%= hidden_field_tag :project_id, @project.id %>

    <br />

    <div align="center">
      <%= submit_tag 'Submit', class: 'btn btn-md btn-primary' %>
    </div>

  <% end %>
</div>

app/views/projects/new.html.erb
<div class="container">
  <h2 class="text-center">New Project</h2>

  <%= form_for @project do |f| %>

    <div class="row">
      <div class="col-md-6 ml-auto mr-auto">
        <%= f.label :title %>
        <%= f.text_field :title, placeholder: "Title of Project", class: "form-control", autofocus: true %>
      </div>
    </div>

    <br />

    <div class="row">
      <div class="col-md-6 ml-auto mr-auto">
        <%= f.label :repo_name, 'Name of Repository on Github' %>
        <%= f.text_field :repo_name, placeholder: "Name of Repository on Github", class: "form-control" %>
      </div>
    </div>

    <br />

    <%= f.hidden_field :owner, value: current_user.id %>

    <div align="center">
      <%= f.submit 'Submit', class: "btn btn-primary btn-md" %>
    </div>

  <% end %>
</div>

app/views/projects/new_issue.html.erb
<div class="container">
  <h2 class="text-center">New Issue</h2>

  <br />

  <%= form_tag create_issue_path(proj_id: @proj_id) do %>

    <div class="row">
      <div class="col-md-6 ml-auto mr-auto">
        <%= text_field_tag :title, nil, placeholder: "Title of Issue", autofocus: true, class: "form-control" %>
      </div>
    </div>

    <br />

    <div class="row">
      <div class="col-md-6 ml-auto mr-auto">
        <%= text_field_tag :body, nil, placeholder: "Description of Issue", class: "form-control" %>
      </div>
    </div>

    <br />

    <div align="center">
      <%= submit_tag 'Submit' %>
    </div>

  <% end %>
</div>

app/views/projects/show.html.erb
<div id="new-feature-holder">
  <div class="new-feature-form">
  </div>
</div>

<div class="container">
  <h2 class="text-center"><%= @project.title %> - Features</h2>

  <% if @owner %>
    <br />

    <div class="row">
      <div class="col-md-8 ml-auto mr-auto">

        <h4 class="text-center" id="user-status">User Status</h4>

        <br />

        <div id="user-status-holder">
          <div class="row">
            <div class="col-6">

              <h6 class="text-center">Confirmed Users</h6>

              <ul class="list-group">
                <% @confirmed_users.each do |cu| %>
                  <li class="list-group-item">
                    <%= cu.username %>
                  </li>
                <% end %>
              </ul>

            </div>

            <div class="col-6">

              <h6 class="text-center">Unconfirmed Users</h6>

              <ul class="list-group">
                <% @unconfirmed_users.each do |uu| %>
                  <li class="list-group-item">
                    <%= uu.username %>
                  </li>
                <% end %>
              </ul>

            </div>
          </div>
        </div>

      </div>
    </div><br />

    <div align="center">
      <%= link_to 'New Feature', new_feature_path(proj_id: @project.id), class: "btn btn-success", remote: true %>
      <%= link_to 'Invite User', invite_users_path(@project.id), class: "btn btn-primary" %>
    </div>

    <br /><br />

  <% end %>

  <br />

  <div class="row">
    <div class="col-md-9">

      <div class="row">
        <div class="col-md-4 ml-auto mr-auto">
          <div id="pending-features">
            <h4 class="text-center show-features-header">Pending Features</h4>

            <ul class="pending-features-ul pending-<%= current_user.username %>">
              <% @pending_features.each do |feat| %>
                <%= render 'uncompleted_feature', feat: feat, proj: @project, user: current_user %>
              <% end %>
            </ul>
          </div>
        </div>

        <div class="col-md-4 ml-auto mr-auto">
          <div id="existing-bugs">
            <h4 class="text-center show-features-header">Existing Bugs</h4>

            <ul class="list-group bug-features-ul pending-<%= current_user.username %>">
              <% @bug_features.each do |feat| %>
                <%= render 'uncompleted_feature', feat: feat, proj: @project, user: current_user %>
              <% end %>
            </ul>
          </div>
        </div>

        <div class="col-md-4 ml-auto mr-auto">
          <div id="completed-features">
            <h4 class="text-center show-features-header">Completed Features</h4>

            <ul class="list-group completed-features-ul">
              <% @completed_features.each do |feat| %>
                <%= render 'completed_feature', feat: feat %>
              <% end %>
            </ul>
          </div>
        </div>
      </div>


    </div>

    <div class="col-md-3">
      <h4 class="text-center" id="nb-title">Notice Board</h4>

      <%= form_for @new_message, remote: true do |f| %>

        <div class="input-group" id="notice-board-form-holder">
          <%= f.text_field :message, placeholder: 'Enter Notice Here', class: 'form-control', id: 'notice-board-message' %>

          <%= f.hidden_field :user_id, value: current_user.id %>
          <%= f.hidden_field :project_id, value: @project.id %>
          <br />

          <span class="input-btn-group">
            <%= f.submit 'Send', class: 'btn btn-default', id: 'notice-board-send' %>
          </span>
        </div>

      <% end %>

      <br />

      <ul class="list-group" id="notice-board">
        <% @messages.each do |m| %>
          <%= render 'messages/message', m: m %>
        <% end %>
      </ul>
    </div>
  </div>


</div>


<script type="text/javascript">
  $(document).ready( function() {
    $('#new-feature-holder').on('click', '#submit-new-feature-form', () => {
      $('#new-feature-holder').fadeOut('1000');
    });

    $('#new-feature-holder').on('click', '#close-new-feature-holder', () => {
      $('#new-feature-holder').fadeOut('1000');
    });

    $('#user-status').click( () => {
      $('#user-status-holder').slideToggle('1000');
    });
  });
</script>