config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { registrations: "users/registrations", sessions: "users/sessions" }
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'home#home'

  mount ActionCable.server, at: '/cable'

  # ~ ~ ~   ~ ~ ~   ~ ~ ~   ~ ~ ~   ~ ~ ~
  #            home controller
  # ~ ~ ~   ~ ~ ~   ~ ~ ~   ~ ~ ~   ~ ~ ~
  get 'dashboard', to: 'home#dashboard'

  # ~ ~ ~   ~ ~ ~   ~ ~ ~   ~ ~ ~   ~ ~ ~
  #          projects controller
  # ~ ~ ~   ~ ~ ~   ~ ~ ~   ~ ~ ~   ~ ~ ~
  resources :projects, only: [:new, :create, :show]
  get 'project/invite/:id', to: 'projects#invite_users', as: 'invite_users'
  post 'projects/invite', to: 'projects#invite_users_create', as: 'invite_users_create'
  get 'project/invite/accept/:proj_id', to: 'projects#accept_project_invitation', as: 'accept_project_invitation'

  # ~ ~ ~   ~ ~ ~   ~ ~ ~   ~ ~ ~   ~ ~ ~
  #          features controller
  # ~ ~ ~   ~ ~ ~   ~ ~ ~   ~ ~ ~   ~ ~ ~
  get 'features/new/:proj_id', to: 'features#new', as: 'new_feature'
  post 'features', to: 'features#create', as: 'features'
  post 'features/:proj_id/completed/:feat_id', to: 'features#feature_completed', as: 'feature_completed'

  # ~ ~ ~   ~ ~ ~   ~ ~ ~   ~ ~ ~   ~ ~ ~
  #          messages controller
  # ~ ~ ~   ~ ~ ~   ~ ~ ~   ~ ~ ~   ~ ~ ~
  resources :messages, only: [:create]
end

app/views/layouts/_alerts.html.erb
<% flash.each do |key, value| %>
  <div class="alert alert-<%= key %>">
    <a href="#" data-dismiss="alert" class="close">×</a>
    <ul>
      <li>
        <%= value %>
      </li>
    </ul>
  </div>
<% end %>


<style media="screen">
  .alert {
    margin-bottom: 0;
  }
  .alert-error {
    background-color: #f2dede;
    border-color: #eed3d7;
    color: #b94a48;
    text-align: left;
  }
  .alert-alert {
    background-color: #f2dede;
    border-color: #eed3d7;
    color: #b94a48;
    text-align: left;
  }
  .alert-success {
    background-color: #dff0d8;
    border-color: #d6e9c6;
    color: #468847;
    text-align: left;
  }
  .alert-notice {
    background-color: #dff0d8;
    border-color: #d6e9c6;
    color: #468847;
    text-align: left;
  }
</style>

app/views/layouts/_footer.html.erb
<footer>
  <p id="footer-text">
    Made with
    <span id="footer-heart">&hearts;</span>
    by Angkiki using
    <span class="badge badge-info">Ruby on Rails</span>
    &copy; 2018
  </p>
</footer>


<style media="screen">
  footer {
    height: 100px;
    background-color: white;
    text-align: center;
    padding: 50px;
    color: black;
    margin-top: 50px;
  }

  #footer-heart {
    color: red;
  }
</style>

app/views/layouts/_nav.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">

  <% if current_user %>
    <%= link_to 'manaGit', dashboard_path, class: 'navbar-brand' %>
  <% else %>
    <%= link_to 'manaGit', root_path, class: 'navbar-brand' %>
  <% end %>

  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">

    <ul class="navbar-nav ml-auto">
      <% if current_user %>
        <li class="nav-item">
          <%= link_to 'Authorise Github', github_auth_path, class: "nav-link" %>
        </li>

        <li class="nav-item">
          <%= link_to 'Log Out', destroy_user_session_path, method: :delete, class: "nav-link" %>
        </li>
      <% else %>
        <li class="nav-item">
          <%= link_to 'Log In', new_user_session_path, class: "nav-link" %>
        </li>

        <li class="nav-item">
          <%= link_to 'Sign Up', new_user_registration_path, class: "nav-link" %>
        </li>
      <% end %>
    </ul>

  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Managit</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= action_cable_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

    <link rel="manifest" href="/manifest.json" />
  </head>

  <body>
    <%= render 'layouts/nav' %>
    <%= render 'layouts/alerts' %>
    <%= yield %>
    <%= render 'layouts/footer' %>
  </body>
</html>